In [ ]:
#Mounting into google drive
from google.colab import drive
drive.mount('/content/gdrive/')

Drive already mounted at /content/gdrive/; to attempt to forcibly remount, call drive.mount("/content/gdrive/", force_remount=True).


In [ ]:
#Importing libraries and dependencies
import cv2 #OpenCv library
import os #Os to navigate through directories
from google.colab.patches import cv2_imshow #Displaying the image
import numpy as np #Numpy
from skimage.util import random_noise #scikit learn to apply random noise
import random
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import math
import pandas as pd
!sudo apt-get update -y
!sudo apt-get install python3.9
#change alternatives
!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1
!sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 2


Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/ InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Ign:5 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  InRelease
Hit:6 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease
Hit:7 http://ppa.launchpad.net/c2d4u.team/c2d4u4.0+/ubuntu bionic InRelease
Hit:8 https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64  Release
Hit:9 http://ppa.launchpad.net/cran/libgit2/ubuntu bionic InRelease
Hit:10 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:11 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease
Hit:12 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu bionic InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency t

In [ ]:
#Now let's check the total number of images in the folder
folder = os.listdir('/content/gdrive/My Drive/pingpong/photos')
total_images = [x for x in folder if x.split('.')[-1]=='jpg']
print('The total number of images in this folders are: {}'.format(len(total_images)))

The total number of images in this folders are: 67


In [ ]:
#Let's create a function for hsv colour range format
def hsv_range(image,color_lower:tuple,color_upper:tuple):
  return cv2.inRange(image,color_lower,color_upper)

In [ ]:
def image_preprocessing(directory,Minvalue:tuple,Maxvalue:tuple): #Since we know that hmin and hmax value is tuple,we are passing hyperparameters as tuple
  image = cv2.imread(directory)
  #Let's blur down the image a bit to reduce the noise in the image
  image = cv2.GaussianBlur(image, (5, 5), 0)
  image = cv2.cvtColor(image,cv2.COLOR_BGR2HSV)
  image = hsv_range(image,Minvalue,Maxvalue)
  return image

In [ ]:
def group_preprocessed(total_image):
  pic_directory = os.listdir(r'/content/gdrive/My Drive/pingpong/photos/')
  pic_directory = pic_directory[:total_image]
  processed_images = []
  for image in pic_directory:
    if image.split('.')[-1]=='jpg':
      src = os.path.join(r'/content/gdrive/My Drive/pingpong/photos/',image) 
      single_image = processed_images.append(image_preprocessing(src,(0,0,173),(179,44,255))) #Passing single images in image_preprocessing function
  return processed_images

In [ ]:
final_images = []
final_centroids = []
for i in range(1,14):
  original_image = cv2.imread('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i))
  output = cv2.connectedComponentsWithStats(image_preprocessing('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i),(0,0,196),(178,49,255)), cv2.CV_32S)
  (numLabels, labels, stats, centroids) = output #Tuples 

  for j in range(0,numLabels):
    # if j==0:
    #   text = 'Examining componeents{}/{}(background)'.format(j,numLabels)
    # else:
    #   text = 'Objects found. Examining {}/{} connected components inside this image'.format(j,numLabels)

    # print('Image info : {}'.format(text))

    x = stats[j, cv2.CC_STAT_LEFT]
    y = stats[j, cv2.CC_STAT_TOP]
    w = stats[j, cv2.CC_STAT_WIDTH]
    h = stats[j, cv2.CC_STAT_HEIGHT]
    area = stats[j, cv2.CC_STAT_AREA]
    (cX, cY) = centroids[j]

    Width_keep = w>10 and w<25
    Height_keep = h>10 and h<25
    Area_keep = area>120 and area<350

    output = original_image.copy()

    if all((Width_keep,Height_keep,Area_keep)):
      print('Connected Components {} and the pic number is {} and the centroid is{}'.format(j,i,[centroids[j]]))
      cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),2)
      cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)
      final_images.append(output)
      final_centroids.append(centroids[j])
    # output = original_image.copy()
    # cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),1)
    # cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)

    # componentMask = (labels == i).astype("uint8")*255 #Converting every labels that the masks detected into white colour
    # cv2_imshow(output)

Connected Components 1 and the pic number is 1 and the centroid is[array([138.39484979,  28.30901288])]
Connected Components 1 and the pic number is 2 and the centroid is[array([139.109375,  42.421875])]
Connected Components 1 and the pic number is 3 and the centroid is[array([139.93040293,  61.55677656])]
Connected Components 1 and the pic number is 4 and the centroid is[array([140.37847222,  85.4375    ])]
Connected Components 1 and the pic number is 5 and the centroid is[array([141.17346939, 113.97619048])]
Connected Components 1 and the pic number is 6 and the centroid is[array([142.05418719, 141.87192118])]
Connected Components 1 and the pic number is 7 and the centroid is[array([141.64224138, 115.60775862])]
Connected Components 1 and the pic number is 8 and the centroid is[array([141.47008547,  91.47435897])]
Connected Components 1 and the pic number is 9 and the centroid is[array([141.48341232,  71.58293839])]
Connected Components 1 and the pic number is 10 and the centroid is[

In [ ]:
for i in range(14,31):
  original_image = cv2.imread('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i))
  output = cv2.connectedComponentsWithStats(image_preprocessing('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i),(0,0,204),(1701,26,255)), cv2.CV_32S)
  (numLabels, labels, stats, centroids) = output #Tuples 

  for j in range(0,numLabels):
    # if j==0:
    #   text = 'Examining componeents{}/{}(background)'.format(j,numLabels)
    # else:
    #   text = 'Objects found. Examining {}/{} connected components inside this image'.format(j,numLabels)

    # print('Image info : {}'.format(text))

    x = stats[j, cv2.CC_STAT_LEFT]
    y = stats[j, cv2.CC_STAT_TOP]
    w = stats[j, cv2.CC_STAT_WIDTH]
    h = stats[j, cv2.CC_STAT_HEIGHT]
    area = stats[j, cv2.CC_STAT_AREA]
    (cX, cY) = centroids[j]

    Width_keep = w>5 and w<16
    Height_keep = h>5 and h<16
    Area_keep = area>50 and area<150

    # Height22,width10,and area is168
    #Height9,width9,and area is63


    output = original_image.copy()


    if all((Width_keep,Height_keep,Area_keep)):
      print('Connected Components found and the pic number is {} and the centroid is{}'.format(i,[centroids[j]]))
      cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),2)
      cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)
      #cv2_imshow(output)
      final_images.append(output)
      final_centroids.append(centroids[j])

    # output = original_image.copy()
    # cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),1)
    # cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)

    # componentMask = (labels == i).astype("uint8")*255 #Converting every labels that the masks detected into white colour
    # cv2_imshow(output)

Connected Components found and the pic number is 14 and the centroid is[array([140.82926829,  39.87804878])]
Connected Components found and the pic number is 15 and the centroid is[array([141.11290323,  45.99193548])]
Connected Components found and the pic number is 16 and the centroid is[array([141.05147059,  56.19852941])]
Connected Components found and the pic number is 17 and the centroid is[array([141.41044776,  69.96268657])]
Connected Components found and the pic number is 18 and the centroid is[array([141.58273381,  87.28776978])]
Connected Components found and the pic number is 19 and the centroid is[array([142.05072464, 107.65217391])]
Connected Components found and the pic number is 20 and the centroid is[array([142.15942029, 130.5       ])]
Connected Components found and the pic number is 21 and the centroid is[array([142.63809524, 126.66666667])]
Connected Components found and the pic number is 22 and the centroid is[array([143.5047619 , 106.53333333])]
Connected Component

In [ ]:
#For frame 31 to 33
for i in range(31,33):
  original_image = cv2.imread('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i))
  output = cv2.connectedComponentsWithStats(image_preprocessing('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i),(0,0,191),(161,255,255)), cv2.CV_32S)
  (numLabels, labels, stats, centroids) = output #Tuples 
  for j in range(0,numLabels):
    # if j==0:
    #   text = 'Examining componeents{}/{}(background)'.format(j,numLabels)
    # else:
    #   text = 'Objects found. Examining {}/{} connected components inside this image'.format(j,numLabels)

    # print('Image info : {}'.format(text))

    x = stats[j, cv2.CC_STAT_LEFT]
    y = stats[j, cv2.CC_STAT_TOP]
    w = stats[j, cv2.CC_STAT_WIDTH]
    h = stats[j, cv2.CC_STAT_HEIGHT]
    area = stats[j, cv2.CC_STAT_AREA]
    (cX, cY) = centroids[j]

    Width_keep = w>5 and w<15
    Height_keep = h>5 and h<15
    Area_keep = area>40 and area<350

    # Height22,width10,and area is168
    #Height9,width9,and area is63

    output = original_image.copy()


    if all((Width_keep,Height_keep,Area_keep)):
      print('Connected Components found and the pic number is {} and the centroid is{}'.format(i,[centroids[j]]))
      cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),2)
      cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)
      #cv2_imshow(output)
      final_images.append(output)
      final_centroids.append(centroids[j])

    # output = original_image.copy()
    # cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),1)
    # cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)

    # componentMask = (labels == i).astype("uint8")*255 #Converting every labels that the masks detected into white colour
    # cv2_imshow(output)

Connected Components found and the pic number is 31 and the centroid is[array([147.25510204,  79.51020408])]
Connected Components found and the pic number is 32 and the centroid is[array([147.75700935,  90.85046729])]


In [ ]:
#For single frame 33
for i in range(33,34):
  original_image = cv2.imread('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i))
  output = cv2.connectedComponentsWithStats(image_preprocessing('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i),(0,0,238),(179,148,255)), cv2.CV_32S)
  (numLabels, labels, stats, centroids) = output #Tuples 

  for j in range(0,numLabels):
    # if j==0:
    #   text = 'Examining componeents{}/{}(background)'.format(j,numLabels)
    # else:
    #   text = 'Objects found. Examining {}/{} connected components inside this image'.format(j,numLabels)

    # print('Image info : {}'.format(text))

    x = stats[j, cv2.CC_STAT_LEFT]
    y = stats[j, cv2.CC_STAT_TOP]
    w = stats[j, cv2.CC_STAT_WIDTH]
    h = stats[j, cv2.CC_STAT_HEIGHT]
    area = stats[j, cv2.CC_STAT_AREA]
    (cX, cY) = centroids[j]

    Width_keep = w>5 and w<7
    Height_keep = h>5 and h<9
    Area_keep = area>35 and area<37

    # Height22,width10,and area is168
    #Height9,width9,and area is63

    output = original_image.copy()

    if all((Width_keep,Height_keep,Area_keep)):
      print('Connected Components found and the pic number is {} and the centroid is{}'.format(i,[centroids[j]]))
      cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),2)
      cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)
      #cv2_imshow(output)
      final_images.append(output)
      final_centroids.append(centroids[j])
    # output = original_image.copy()
    # cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),1)
    # cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)

    # componentMask = (labels == i).astype("uint8")*255 #Converting every labels that the masks detected into white colour
    # cv2_imshow(output)

Connected Components found and the pic number is 33 and the centroid is[array([149.58333333, 118.02777778])]


In [ ]:
#For single frame 34
for i in range(34,35):
  original_image = cv2.imread('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i))
  output = cv2.connectedComponentsWithStats(image_preprocessing('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i),(0,0,227),(179,255,255)), cv2.CV_32S)
  (numLabels, labels, stats, centroids) = output #Tuples 

  for j in range(0,numLabels):
    # if j==0:
    #   text = 'Examining componeents{}/{}(background)'.format(j,numLabels)
    # else:
    #   text = 'Objects found. Examining {}/{} connected components inside this image'.format(j,numLabels)

    # print('Image info : {}'.format(text))

    x = stats[j, cv2.CC_STAT_LEFT]
    y = stats[j, cv2.CC_STAT_TOP]
    w = stats[j, cv2.CC_STAT_WIDTH]
    h = stats[j, cv2.CC_STAT_HEIGHT]
    area = stats[j, cv2.CC_STAT_AREA]
    (cX, cY) = centroids[j]

    Height_keep = h>5 and h<9
    Width_keep = w>5 and w<10
    Area_keep = area>30 and area<37

    # Height22,width10,and area is168
    #Height9,width9,and area is63
    #Height6,width9,and area is33

    output = original_image.copy()

    if all((Width_keep,Height_keep,Area_keep)):
      print('Connected Components found and the pic number is {} and the centroid is{}'.format(i,[centroids[j]]))
      cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),2)
      cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)
      #cv2_imshow(output)
      final_images.append(output)
      final_centroids.append(centroids[j])

    # output = original_image.copy()
    # cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),1)
    # cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)

    # componentMask = (labels == i).astype("uint8")*255 #Converting every labels that the masks detected into white colour
    # cv2_imshow(output)

Connected Components found and the pic number is 34 and the centroid is[array([147.39393939, 131.66666667])]


In [ ]:
#For single frame 35 to 47
for i in range(35,47):
  original_image = cv2.imread('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i))
  output = cv2.connectedComponentsWithStats(image_preprocessing('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i),(0,0,182),(173,127,255)), cv2.CV_32S)
  (numLabels, labels, stats, centroids) = output #Tuples 

  for j in range(0,numLabels):
    # if j==0:
    #   text = 'Examining componeents{}/{}(background)'.format(j,numLabels)
    # else:
    #   text = 'Objects found. Examining {}/{} connected components inside this image'.format(j,numLabels)

    # print('Image info : {}'.format(text))

    x = stats[j, cv2.CC_STAT_LEFT]
    y = stats[j, cv2.CC_STAT_TOP]
    w = stats[j, cv2.CC_STAT_WIDTH]
    h = stats[j, cv2.CC_STAT_HEIGHT]
    area = stats[j, cv2.CC_STAT_AREA]
    (cX, cY) = centroids[j]

    Height_keep = h>5 and h<25
    Width_keep = w>30 and w<50
    Area_keep = area>200 and area<350

    # Height22,width10,and area is168
    #Height9,width9,and area is63
    #Height6,width9,and area is33
    #Height8,width19,and area is77
    #Height16,width39,and area is338

    output = original_image.copy()


    if all((Width_keep,Height_keep,Area_keep)):
      print('Connected Components found and the pic number is {} and the centroid is{}'.format(i,[centroids[j]]))
      cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),2)
      cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)
      #cv2_imshow(output)
      final_images.append(output)
      final_centroids.append(centroids[j])
    # output = original_image.copy()
    # cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),1)
    # cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)

    # componentMask = (labels == i).astype("uint8")*255 #Converting every labels that the masks detected into white colour
    # cv2_imshow(output)

Connected Components found and the pic number is 35 and the centroid is[array([155.69230769, 127.5591716 ])]
Connected Components found and the pic number is 36 and the centroid is[array([158.50671141, 126.46979866])]
Connected Components found and the pic number is 37 and the centroid is[array([161.07801418, 125.14539007])]
Connected Components found and the pic number is 38 and the centroid is[array([163.2369338 , 123.68292683])]
Connected Components found and the pic number is 39 and the centroid is[array([165.63851351, 121.48310811])]
Connected Components found and the pic number is 40 and the centroid is[array([166.94809689, 118.79930796])]
Connected Components found and the pic number is 41 and the centroid is[array([168.42160279, 114.63066202])]
Connected Components found and the pic number is 42 and the centroid is[array([168.96308725, 109.56375839])]
Connected Components found and the pic number is 43 and the centroid is[array([169.91694352, 102.88039867])]
Connected Component

In [ ]:
#For single frame 47 to 55
for i in range(47,48):
  original_image = cv2.imread('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i))
  output = cv2.connectedComponentsWithStats(image_preprocessing('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i),(0,0,205),(179,255,255)), cv2.CV_32S)
  (numLabels, labels, stats, centroids) = output #Tuples 


  for j in range(0,numLabels):
    # if j==0:
    #   text = 'Examining componeents{}/{}(background)'.format(j,numLabels)
    # else:
    #   text = 'Objects found. Examining {}/{} connected components inside this image'.format(j,numLabels)

    # print('Image info : {}'.format(text))

    x = stats[j, cv2.CC_STAT_LEFT]
    y = stats[j, cv2.CC_STAT_TOP]
    w = stats[j, cv2.CC_STAT_WIDTH]
    h = stats[j, cv2.CC_STAT_HEIGHT]
    area = stats[j, cv2.CC_STAT_AREA]
    (cX, cY) = centroids[j]

    Height_keep = h>5 and h<25
    Width_keep = w>5 and w<50
    Area_keep = area>30 and area<40

    # Height22,width10,and area is168
    #Height9,width9,and area is63
    #Height6,width9,and area is33
    #Height8,width19,and area is77
    #Height16,width39,and area is338

    output = original_image.copy()

    if all((Width_keep,Height_keep,Area_keep)):
      print('Connected Components found and the pic number is {} and the centroid is{}'.format(i,[centroids[j]]))
      cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),2)
      cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)
      #cv2_imshow(output)
      final_images.append(output)
      final_centroids.append(centroids[j])

    # output = original_image.copy()
    # cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),1)
    # cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)

    # componentMask = (labels == i).astype("uint8")*255 #Converting every labels that the masks detected into white colour
    # cv2_imshow(output)

Connected Components found and the pic number is 47 and the centroid is[array([170.12121212,  81.36363636])]


In [ ]:
#For single frame 48 to 54
for i in range(48,60):
  original_image = cv2.imread('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i))
  output = cv2.connectedComponentsWithStats(image_preprocessing('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i),(0,9,178),(42,60,253)), cv2.CV_32S)
  (numLabels, labels, stats, centroids) = output #Tuples 

  for j in range(0,numLabels):
    # if j==0:
    #   text = 'Examining componeents{}/{}(background)'.format(j,numLabels)
    # else:
    #   text = 'Objects found. Examining {}/{} connected components inside this image'.format(j,numLabels)

    # print('Image info : {}'.format(text))

    x = stats[j, cv2.CC_STAT_LEFT]
    y = stats[j, cv2.CC_STAT_TOP]
    w = stats[j, cv2.CC_STAT_WIDTH]
    h = stats[j, cv2.CC_STAT_HEIGHT]
    area = stats[j, cv2.CC_STAT_AREA]
    (cX, cY) = centroids[j]

    Height_keep = h>4 and h<10
    Width_keep = w>4 and w<10
    Area_keep = area>28 and area<35

    # Height22,width10,and area is168
    #Height9,width9,and area is63
    #Height6,width9,and area is33
    #Height8,width19,and area is77
    #Height16,width39,and area is338
    #Height6,width7,and area is31

    output = original_image.copy()

    if all((Width_keep,Height_keep,Area_keep)):
      print('Connected Components found and the pic number is {} and the centroid is{}'.format(i,[centroids[j]]))
      cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),2)
      cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)
      #cv2_imshow(output)
      final_images.append(output)
      final_centroids.append(centroids[j])
      
    # output = original_image.copy()
    # cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),1)
    # cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)

    # componentMask = (labels == i).astype("uint8")*255 #Converting every labels that the masks detected into white colour
    # cv2_imshow(output)

Connected Components found and the pic number is 48 and the centroid is[array([172.03030303,  77.81818182])]
Connected Components found and the pic number is 49 and the centroid is[array([174.25806452,  77.25806452])]
Connected Components found and the pic number is 50 and the centroid is[array([176.13333333,  78.46666667])]
Connected Components found and the pic number is 51 and the centroid is[array([178.12903226,  81.4516129 ])]
Connected Components found and the pic number is 52 and the centroid is[array([179.63333333,  85.36666667])]
Connected Components found and the pic number is 53 and the centroid is[array([181.38709677,  91.38709677])]
Connected Components found and the pic number is 54 and the centroid is[array([182.5862069 ,  97.86206897])]


In [ ]:
#For single frame 55 to 56
for i in range(55,56):
  original_image = cv2.imread('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i))
  output = cv2.connectedComponentsWithStats(image_preprocessing('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i),(0,0,0),(179,44,255)), cv2.CV_32S)
  (numLabels, labels, stats, centroids) = output #Tuples 

  for j in range(0,numLabels):
    # if j==0:
    #   text = 'Examining componeents{}/{}(background)'.format(j,numLabels)
    # else:
    #   text = 'Objects found. Examining {}/{} connected components inside this image'.format(j,numLabels)

    # print('Image info : {}'.format(text))

    x = stats[j, cv2.CC_STAT_LEFT]
    y = stats[j, cv2.CC_STAT_TOP]
    w = stats[j, cv2.CC_STAT_WIDTH]
    h = stats[j, cv2.CC_STAT_HEIGHT]
    area = stats[j, cv2.CC_STAT_AREA]
    (cX, cY) = centroids[j]

    Height_keep = h>4 and h<9
    Width_keep = w>4 and w<12
    Area_keep = area>28 and area<50

    output = original_image.copy()

    if all((Width_keep,Height_keep,Area_keep)):
      print('Connected Components found and the pic number is {} and the centroid is{}'.format(i,[centroids[j]]))
      cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),2)
      cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)
      #cv2_imshow(output)
      final_images.append(output)
      final_centroids.append(centroids[j])

    # output = original_image.copy()
    # cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),1)
    # cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)

    # componentMask = (labels == i).astype("uint8")*255 #Converting every labels that the masks detected into white colour
    # cv2_imshow(output)

Connected Components found and the pic number is 55 and the centroid is[array([185.13953488, 107.34883721])]


In [ ]:
#For single frame 56 to 60
for i in range(56,60):
  original_image = cv2.imread('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i))
  output = cv2.connectedComponentsWithStats(image_preprocessing('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i),(17,0,0),(179,27,255)), cv2.CV_32S)
  (numLabels, labels, stats, centroids) = output #Tuples 

  for j in range(0,numLabels):
    # if j==0:
    #   text = 'Examining componeents{}/{}(background)'.format(j,numLabels)
    # else:
    #   text = 'Objects found. Examining {}/{} connected components inside this image'.format(j,numLabels)

    # print('Image info : {}'.format(text))

    x = stats[j, cv2.CC_STAT_LEFT]
    y = stats[j, cv2.CC_STAT_TOP]
    w = stats[j, cv2.CC_STAT_WIDTH]
    h = stats[j, cv2.CC_STAT_HEIGHT]
    area = stats[j, cv2.CC_STAT_AREA]
    (cX, cY) = centroids[j]

    Height_keep = h>4 and h<10
    Width_keep = w>4 and w<10
    Area_keep = area>40 and area<45

    output = original_image.copy()

    if all((Width_keep,Height_keep,Area_keep)):
      print('Connected Components found and the pic number is {} and the centroid is{}'.format(i,[centroids[j]]))
      cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),2)
      cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)
      #cv2_imshow(output)
      final_images.append(output)
      final_centroids.append(centroids[j])

    # output = original_image.copy()
    # cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),1)
    # cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)

    # componentMask = (labels == i).astype("uint8")*255 #Converting every labels that the masks detected into white colour
    # cv2_imshow(output)

Connected Components found and the pic number is 56 and the centroid is[array([175.9047619 , 115.23809524])]


In [ ]:
#For single frame 57 
for i in range(57,60):
  original_image = cv2.imread('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i))
  output = cv2.connectedComponentsWithStats(image_preprocessing('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i),(0,0,200),(31,46,240)), cv2.CV_32S)
  (numLabels, labels, stats, centroids) = output #Tuples 


  for j in range(0,numLabels):
    # if j==0:
    #   text = 'Examining componeents{}/{}(background)'.format(j,numLabels)
    # else:
    #   text = 'Objects found. Examining {}/{} connected components inside this image'.format(j,numLabels)

    # print('Image info : {}'.format(text))

    x = stats[j, cv2.CC_STAT_LEFT]
    y = stats[j, cv2.CC_STAT_TOP]
    w = stats[j, cv2.CC_STAT_WIDTH]
    h = stats[j, cv2.CC_STAT_HEIGHT]
    area = stats[j, cv2.CC_STAT_AREA]
    (cX, cY) = centroids[j]

    Height_keep = h>4 and h<10
    Width_keep = w>4 and w<11
    Area_keep = area>30 and area<40

    output = original_image.copy()

    if all((Width_keep,Height_keep,Area_keep)):
      print('Connected Components found and the pic number is {} and the centroid is{}'.format(i,[centroids[j]]))
      cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),2)
      cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)
      #cv2_imshow(output)
      final_images.append(output)
      final_centroids.append(centroids[j])

    # output = original_image.copy()
    # cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),1)
    # cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)

    # componentMask = (labels == i).astype("uint8")*255 #Converting every labels that the masks detected into white colour
    # cv2_imshow(output)

Connected Components found and the pic number is 57 and the centroid is[array([156.90322581, 128.32258065])]


In [ ]:
#For single frame 578 
for i in range(58,59):
  original_image = cv2.imread('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i))
  output = cv2.connectedComponentsWithStats(image_preprocessing('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i),(22,0,187),(179,255,255)), cv2.CV_32S)
  (numLabels, labels, stats, centroids) = output #Tuples 


  for j in range(0,numLabels):
    # if j==0:
    #   text = 'Examining componeents{}/{}(background)'.format(j,numLabels)
    # else:
    #   text = 'Objects found. Examining {}/{} connected components inside this image'.format(j,numLabels)

    # print('Image info : {}'.format(text))

    x = stats[j, cv2.CC_STAT_LEFT]
    y = stats[j, cv2.CC_STAT_TOP]
    w = stats[j, cv2.CC_STAT_WIDTH]
    h = stats[j, cv2.CC_STAT_HEIGHT]
    area = stats[j, cv2.CC_STAT_AREA]
    (cX, cY) = centroids[j]

    Height_keep = h>4 and h<10
    Width_keep = w>4 and w<11
    Area_keep = area>32 and area<36

    output = original_image.copy()

    if all((Width_keep,Height_keep,Area_keep)):
      print('Connected Components found and the pic number is {} and the centroid is{}'.format(i,[centroids[j]]))
      cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),2)
      cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)
      #cv2_imshow(output)
      final_images.append(output)
      final_centroids.append(centroids[j])

    # output = original_image.copy()
    # cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),1)
    # cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)

    # componentMask = (labels == i).astype("uint8")*255 #Converting every labels that the masks detected into white colour
    # cv2_imshow(output)

Connected Components found and the pic number is 58 and the centroid is[array([136.08571429, 143.37142857])]


In [ ]:
#For single frame 59 
for i in range(59,60):
  original_image = cv2.imread('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i))
  output = cv2.connectedComponentsWithStats(image_preprocessing('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i),(26,14,174),(74,47,235)), cv2.CV_32S)
  (numLabels, labels, stats, centroids) = output #Tuples 


  for j in range(0,numLabels):
    # if j==0:
    #   text = 'Examining componeents{}/{}(background)'.format(j,numLabels)
    # else:
    #   text = 'Objects found. Examining {}/{} connected components inside this image'.format(j,numLabels)

    # print('Image info : {}'.format(text))

    x = stats[j, cv2.CC_STAT_LEFT]
    y = stats[j, cv2.CC_STAT_TOP]
    w = stats[j, cv2.CC_STAT_WIDTH]
    h = stats[j, cv2.CC_STAT_HEIGHT]
    area = stats[j, cv2.CC_STAT_AREA]
    (cX, cY) = centroids[j]

    Height_keep = h>4 and h<10
    Width_keep = w>4 and w<13
    Area_keep = area>50 and area<56


    output = original_image.copy()

    if all((Width_keep,Height_keep,Area_keep)):
      print('Connected Components found and the pic number is {} and the centroid is{}'.format(i,[centroids[j]]))
      cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),2)
      cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)
      final_images.append(output)
      final_centroids.append(centroids[j])


    # output = original_image.copy()
    # cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),1)
    # cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)

    # componentMask = (labels == i).astype("uint8")*255 #Converting every labels that the masks detected into white colour
    # cv2_imshow(output)

Connected Components found and the pic number is 59 and the centroid is[array([116.65454545, 158.52727273])]


In [ ]:
#For single frame 60 
for i in range(60,61):
  original_image = cv2.imread('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i))
  output = cv2.connectedComponentsWithStats(image_preprocessing('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i),(36,6,156),(80,20,255)), cv2.CV_32S)
  (numLabels, labels, stats, centroids) = output #Tuples 


  for j in range(0,numLabels):
    # if j==0:
    #   text = 'Examining componeents{}/{}(background)'.format(j,numLabels)
    # else:
    #   text = 'Objects found. Examining {}/{} connected components inside this image'.format(j,numLabels)

    # print('Image info : {}'.format(text))

    x = stats[j, cv2.CC_STAT_LEFT]
    y = stats[j, cv2.CC_STAT_TOP]
    w = stats[j, cv2.CC_STAT_WIDTH]
    h = stats[j, cv2.CC_STAT_HEIGHT]
    area = stats[j, cv2.CC_STAT_AREA]
    (cX, cY) = centroids[j]

    Height_keep = h>4 and h<11
    Width_keep = w>4 and w<13
    Area_keep = area>45 and area<50


    output = original_image.copy()

    if all((Width_keep,Height_keep,Area_keep)):
      print('Connected Components found and the pic number is {} and the centroid is{}'.format(i,[centroids[j]]))
      cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),2)
      cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)
      #cv2_imshow(output)
      final_images.append(output)
      final_centroids.append(centroids[j])

Connected Components found and the pic number is 60 and the centroid is[array([ 99.39583333, 156.52083333])]


In [ ]:
#For last frame 61
for i in range(61,62):
  original_image = cv2.imread('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i))
  output = cv2.connectedComponentsWithStats(image_preprocessing('/content/gdrive/My Drive/pingpong/photos/stennis{}.jpg'.format(i),(20,2,179),(75,57,251)), cv2.CV_32S)
  (numLabels, labels, stats, centroids) = output #Tuples 


  for j in range(0,numLabels):
    # if j==0:
    #   text = 'Examining componeents{}/{}(background)'.format(j,numLabels)
    # else:
    #   text = 'Objects found. Examining {}/{} connected components inside this image'.format(j,numLabels)

    # print('Image info : {}'.format(text))

    x = stats[j, cv2.CC_STAT_LEFT]
    y = stats[j, cv2.CC_STAT_TOP]
    w = stats[j, cv2.CC_STAT_WIDTH]
    h = stats[j, cv2.CC_STAT_HEIGHT]
    area = stats[j, cv2.CC_STAT_AREA]
    (cX, cY) = centroids[j]

    Height_keep = h>6 and h<8
    Width_keep = w>9 and w<11
    Area_keep = area>42 and area<45

    output = original_image.copy()

    if all((Width_keep,Height_keep,Area_keep)):
      print('Connected Components found and the pic number is {} and the centroid is{}'.format(i,[centroids[j]]))
      cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),2)
      cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)
      #cv2_imshow(output)
      final_images.append(output)
      final_centroids.append(centroids[j])

Connected Components found and the pic number is 61 and the centroid is[array([ 81.81395349, 152.90697674])]


In [ ]:
#To import the final_images(all the pixel array of an image into a file)
import pickle
with open("final_images", "wb") as fp:   #Pickling
  pickle.dump(final_images, fp)

In [ ]:
with open("final_centroids", "wb") as fp:   #Pickling
  pickle.dump(final_centroids, fp)

In [ ]:
vel_per_frame = [] #Extracting velocity per frame in every frame
for i in range(0,len(final_centroids)):
  for j in range(0,1):
    if i==0:
      vel_per_frame.append(0.0)
    else:
      first_array = [final_centroids[j][j],final_centroids[j][j+1]]
      second_array = [final_centroids[j+1][j],final_centroids[j+1][j+1]]
      distance_pixel = math.dist(int(first_array),int(second_array))
      vel_per_frame.append(math.dist(first_array,second_array))
      final_centroids.remove(final_centroids[0])
      

        #vel_per_frame.append((final_centroids[i][j] - final_centroids[i][j+1])+(final_centroids[i+1][j] - final_centroids[j+1][j+1]))


AttributeError: ignored

In [ ]:
vel_per_frame

[0.0]

In [ ]:
final_centroids

[array([138.39484979,  28.30901288]),
 array([139.109375,  42.421875]),
 array([139.93040293,  61.55677656]),
 array([140.37847222,  85.4375    ]),
 array([141.17346939, 113.97619048]),
 array([142.05418719, 141.87192118]),
 array([141.64224138, 115.60775862]),
 array([141.47008547,  91.47435897]),
 array([141.48341232,  71.58293839]),
 array([141.485,  56.665]),
 array([141.1420765,  46.0273224]),
 array([140.92857143,  40.21428571]),
 array([140.80503145,  38.19496855]),
 array([140.82926829,  39.87804878]),
 array([141.11290323,  45.99193548]),
 array([141.05147059,  56.19852941]),
 array([141.41044776,  69.96268657]),
 array([141.58273381,  87.28776978]),
 array([142.05072464, 107.65217391]),
 array([142.15942029, 130.5       ]),
 array([142.63809524, 126.66666667]),
 array([143.5047619 , 106.53333333]),
 array([143.57894737,  90.14736842]),
 array([144.12195122,  77.52439024]),
 array([144.94520548,  68.16438356]),
 array([145.14492754,  62.86956522]),
 array([145.74137931,  60.22

In [ ]:
# original_image = cv2.imread('/content/gdrive/My Drive/pingpong/photos/stennis61.jpg')
# image = image_preprocessing('/content/gdrive/My Drive/pingpong/photos/stennis61.jpg',(20,2,179),(75,57,251))


# # apply connected component analysis to the thresholded image
# output = cv2.connectedComponentsWithStats(image, cv2.CV_32S)
# (numLabels, labels, stats, centroids) = output #Tuples 



# '''
# The cv2.connectedComponentsWithStats then returns a 4-tuple of:
# - The total number of unique labels (i.e., number of total components) that were detected
# - A mask named labels has the same spatial dimensions as our input thresh image. 
# - For each location in labels, we have an integer ID value that corresponds to the connected component where the pixel belongs. 
# - stats: Statistics on each connected component, including the bounding box coordinates and area (in pixels).
# - The centroids (i.e., center) (x, y)-coordinates of each connected component.

# '''
# for i in range(numLabels):
#   if i==0:
#     text = 'Examining components{}/{} (background)'.format(i,numLabels)
#   else:
#     text = 'Objects found. Examining {}/{} connected components inside this image'.format(i,numLabels)


#   x = stats[i, cv2.CC_STAT_LEFT]
#   y = stats[i, cv2.CC_STAT_TOP]
#   w = stats[i, cv2.CC_STAT_WIDTH]
#   h = stats[i, cv2.CC_STAT_HEIGHT]
#   area = stats[i, cv2.CC_STAT_AREA]
#   (cX, cY) = centroids[i]

#   output = original_image.copy()

#   print('Height{},width{},and area is{}'.format(h,w,area))
#   cv2.rectangle(output, (x, y), (x + w, y + h), (255, 255, 0),1)
#   cv2.circle(output, (int(cX), int(cY)),1, (0, 0, 255), -1)

#   componentMask = (labels == i).astype("uint8")*255 #Converting every labels that the masks detected into white colour
#   cv2_imshow(output)

#     #   Width_keep = w>13 and w<25
#     # Height_keep = h>13 and h<25
#     # Area_keep = area>120 and area<350

In [ ]:
import pickle
import math

with open("/Users/shikharghimire/Desktop/tabletennis/final_centroids", "rb") as fp:
    final_centroids = pickle.load(fp)
        


vel_per_frame = [] #Extracting velocity per frame in every frame
for i in range(0,len(final_centroids)):
  for j in range(0,1):
    if i==0:
      vel_per_frame.append(0.0)
    else:
      first_array = [final_centroids[j][j],final_centroids[j][j+1]]
      second_array = [final_centroids[j+1][j],final_centroids[j+1][j+1]]
      distance_pixel = math.dist(int(first_array),int(second_array))
      vel_per_frame.append(math.dist(first_array,second_array))
      final_centroids.remove(final_centroids[0])
      

        #vel_per_frame.append((final_centroids[i][j] - final_centroids[i][j+1])+(final_centroids[i+1][j] - final_centroids[j+1][j+1]))


In [ ]:
#For animmated graph
#https://holypython.com/python-visualization-tutorial/guide-to-python-animations-animating-line-charts/#

In [ ]:
# #Let's subplot the images with hsv colour range
# #Feeding raw dog images into preprocessing function and saving it into dogs_preprocessed folder
# pic_directory = os.listdir(r'/content/gdrive/My Drive/pingpong/photos/')
# pic_directory = pic_directory[:20]
# processed_images = []
# for image in pic_directory:
#     if image.split('.')[-1]=='jpg':
#       src = os.path.join(r'/content/gdrive/My Drive/pingpong/photos/',image) 
#       single_image = processed_images.append(image_preprocessing(src)) #Passing single images in image_preprocessing function

In [ ]:
# def image_preprocessing(directory,thresh):
#   image = cv2.imread(directory)
#   #Let's blur down the image a bit to reduce the noise in the image
#   image = cv2.blur(image,(5,5))
#   image = cv2.cvtColor(image,cv2.COLOR_BGR2HSV)
#   #Let's use binarization on the image
#   thresh_ball,image = cv2.threshold(image,thresh,255,cv2.THRESH_BINARY_INV)
#   return image

In [ ]:
# pic_directory = os.listdir(r'/content/gdrive/My Drive/pingpong/photos/')

In [ ]:
# #Feeding raw dog images into preprocessing function and saving it into dogs_preprocessed folder
# processed_images = []
# for image in pic_directory:
#     if image.split('.')[-1]=='jpg':
#       src = os.path.join(r'/content/gdrive/My Drive/pingpong/photos/',image) 
#       single_image = processed_images.append(image_preprocessing(src,80)) #Passing single images in image_preprocessing function .Previous was 45
# figure = plt.figure(figsize = (20,20))
# cols = 5
# rows = 5
# for i in range(20):
#   ax1 = figure.add_subplot(rows,cols,i+1)
#   image_random = random.choice(processed_images)
#   plt.imshow(image_random,)

# plt.show()



In [ ]:
#Now what we want to do is seperate the ball colour with rest of the colour objects

# pink_lower = (22,0,241)
# pink_upper = (179,255,255)

# ####For first 30 frames
# # pink_lower = (22,0,241)
# # pink_upper = (179,255,255)

# #(hMin = 26 , sMin = 0, vMin = 171), (hMax = 78 , sMax = 40, vMax = 255) -> Once the bat hits the ball

# mask = cv2.inRange(image, pink_lower, pink_upper)